export const BREAKFAST_IDEAS = [
  "Jajecznica", "Jajka sadzone", "Pasta jajeczna", "Omlety", "Tosty francuskie",
  "Płatki z mlekiem", "Owsianka/Granola z jogurtem i owocami", "Szakszuka",
  "Tosty z patelni", "Parówki", "Hot dogi śniadaniowe", "Naleśniki",
  "Quesadilla z patelni", "Twarożek z rzodkiewką i szczypiorkiem",
  "Serek wiejski z dodatkami", "Guacamole",
];

export const PRODUCTS = [
  ["Chleb pszenny", "Pieczywo", "szt."], ["Chleb razowy", "Pieczywo", "szt."],
  ["Chleb tostowy", "Pieczywo", "opak."], ["Chleb bezglutenowy", "Pieczywo", "szt."],
  ["Bułki kajzerki", "Pieczywo", "szt."], ["Bułki grahamki", "Pieczywo", "szt."],
  ["Bagietki", "Pieczywo", "szt."], ["Tortille", "Pieczywo", "opak."],
  ["Ser gouda w plastrach (lub inny)", "Nabiał i zamienniki", "opak."],
  ["Mozzarella tarta/kulka", "Nabiał i zamienniki", "opak."],
  ["Camembert", "Nabiał i zamienniki", "szt."], ["Ser bez laktozy", "Nabiał i zamienniki", "opak."],
  ["Ser wegański", "Nabiał i zamienniki", "opak."],
  ["Twaróg chudy/tłusty/półtłusty", "Nabiał i zamienniki", "opak."],
  ["Twarożek kanapkowy śmietankowy", "Nabiał i zamienniki", "opak."],
  ["Hummus", "Nabiał i zamienniki", "opak."], ["Serek wiejski", "Nabiał i zamienniki", "szt."],
  ["Skyr Naturalny", "Nabiał i zamienniki", "szt."], ["Skyr owocowy", "Nabiał i zamienniki", "szt."],
  ["Skyr waniliowy", "Nabiał i zamienniki", "szt."], ["Passata pomidorowa", "Dodatki", "szt."],
  ["Suszone pomidory", "Dodatki", "słoik"],
  ["Szynka", "Mięso i zamienniki", "opak."], ["Schab w plastrach", "Mięso i zamienniki", "opak."],
  ["Salami", "Mięso i zamienniki", "opak."], ["Kabanosy", "Mięso i zamienniki", "opak."],
  ["Boczek", "Mięso i zamienniki", "opak."], ["Parówki", "Mięso i zamienniki", "szt."],
  ["Pasztet", "Mięso i zamienniki", "opak."], ["Ryba wędzona", "Mięso i zamienniki", "opak."],
  ["Wege parówki", "Mięso i zamienniki", "opak."], ["Wege kabanosy", "Mięso i zamienniki", "opak."],
  ["Wege szynka", "Mięso i zamienniki", "opak."], ["Jajka", "Nabiał i zamienniki", "szt."],
  ["Pomidory", "Warzywa", "szt."], ["Ogórki", "Warzywa", "szt."], ["Papryka", "Warzywa", "szt."],
  ["Sałata", "Warzywa", "szt."], ["Rukola", "Warzywa", "opak."], ["Rzodkiewki", "Warzywa", "pęczek"],
  ["Szczypiorek", "Warzywa", "pęczek"], ["Cebula czerwona/żółta", "Warzywa", "szt."],
  ["Awokado", "Warzywa", "szt."], ["Oliwki zielone/czarne", "Warzywa", "słoik"],
  ["Ogórki kiszone", "Warzywa", "słoik"], ["Kukurydza", "Warzywa", "puszka"],
  ["Mleko", "Śniadaniowe", "l"], ["Jogurt naturalny", "Śniadaniowe", "szt."],
  ["Śmietana 18/30", "Śniadaniowe", "szt."], ["Płatki kukurydziane", "Śniadaniowe", "opak."],
  ["Płatki czekoladowe", "Śniadaniowe", "opak."], ["Musli", "Śniadaniowe", "opak."],
  ["Granola", "Śniadaniowe", "opak."], ["Owsianka", "Śniadaniowe", "opak."],
  ["Krem czekoladowy", "Śniadaniowe", "słoik"], ["Dżem", "Śniadaniowe", "słoik"],
  ["Rodzynki", "Śniadaniowe", "opak."], ["Masło", "Śniadaniowe", "szt."],
  ["Wege masło", "Śniadaniowe", "szt."], ["Mąka", "Śniadaniowe", "kg"],
  ["Cukier", "Śniadaniowe", "kg"], ["Cukier wanilinowy", "Śniadaniowe", "opak."],
  ["Olej", "Śniadaniowe", "l"], ["Banany", "Owoce", "szt."], ["Jabłka", "Owoce", "szt."],
  ["Gruszki", "Owoce", "szt."], ["Winogrona", "Owoce", "opak."], ["Truskawki", "Owoce", "opak."],
].map(([name, category, unit], index) => ({
  id: `demo-${index + 1}`, name, category, unit, sort_order: index + 1,
}));
