export const BREAKFAST_RECIPES = [
  {
    name: "Jajecznica", category: "Na ciepło", time: "15 min", difficulty: "łatwe",
    ingredients: ["16–20 jajek", "40–50 g masła lub 3 łyżki oleju", "sól i pieprz", "opcjonalnie: 1 pęczek szczypiorku, 200 g boczku lub 4 pomidory"],
    steps: ["Rozgrzej patelnię na małym ogniu i dodaj tłuszcz.", "Roztrzep jajka z solą i pieprzem.", "Wlej jajka i mieszaj powoli, aż się zetną, ale pozostaną kremowe.", "Dodatki podsmaż wcześniej lub dodaj pod koniec."],
    tip: "Na jednej patelni przygotuj maksymalnie porcję dla 4–5 osób — większa ilość łatwo robi się sucha.",
  },
  {
    name: "Jajka sadzone", category: "Na ciepło", time: "12 min", difficulty: "łatwe",
    ingredients: ["14–16 jajek", "40 g masła lub 3 łyżki oleju", "sól i pieprz", "14–16 kromek pieczywa"],
    steps: ["Rozgrzej niewielką ilość tłuszczu.", "Wbij jajka tak, aby nie uszkodzić żółtek.", "Smaż pod przykryciem na małym ogniu do ścięcia białka.", "Dopraw i podawaj od razu z pieczywem."],
    tip: "Pokrywka przyspiesza ścinanie białka i ogranicza zużycie gazu.",
  },
  {
    name: "Pasta jajeczna", category: "Bez gotowania", time: "20 min", difficulty: "łatwe",
    ingredients: ["8–10 jajek", "4–5 łyżek majonezu lub jogurtu", "1 pęczek szczypiorku", "sól i pieprz", "14–16 kromek pieczywa"],
    steps: ["Ugotuj jajka na twardo przez około 9 minut.", "Ostudź, obierz i drobno posiekaj.", "Wymieszaj z majonezem lub jogurtem i szczypiorkiem.", "Dopraw i nakładaj na pieczywo."],
    tip: "Jajka można ugotować wieczorem, co znacznie skraca poranne przygotowanie.",
  },
  {
    name: "Omlet", category: "Na ciepło", time: "18 min", difficulty: "średnie",
    ingredients: ["16–20 jajek", "200 ml mleka", "40 g masła lub 3 łyżki oleju", "250–300 g sera", "300–400 g warzyw lub szynki"],
    steps: ["Roztrzep jajka z mlekiem i przyprawami.", "Podsmaż wybrane dodatki.", "Wlej masę jajeczną i smaż pod przykryciem na małym ogniu.", "Dodaj ser, złóż omlet na pół i podgrzewaj jeszcze minutę."],
    tip: "Cieńsze omlety łatwiej obrócić na małej jachtowej patelni.",
  },
  {
    name: "Tosty francuskie", category: "Na słodko", time: "20 min", difficulty: "łatwe",
    ingredients: ["14–16 kromek chleba", "4–5 jajek", "400 ml mleka", "50 g masła", "3 łyżki cukru i 1 łyżeczka cynamonu", "500 g owoców lub 1 słoik dżemu"],
    steps: ["Roztrzep jajka z odrobiną mleka.", "Zanurz kromki z obu stron.", "Smaż na maśle do złotego koloru.", "Podawaj z owocami, dżemem albo cukrem z cynamonem."],
    tip: "To dobry sposób na wykorzystanie lekko czerstwego pieczywa.",
  },
  {
    name: "Płatki z mlekiem", category: "Ekspresowe", time: "5 min", difficulty: "bardzo łatwe",
    ingredients: ["500–600 g płatków kukurydzianych, czekoladowych lub musli", "1,5–2 l mleka albo napoju roślinnego", "opcjonalnie: 4 banany i 100 g rodzynek"],
    steps: ["Wsyp płatki do misek.", "Dodaj owoce lub rodzynki.", "Zalej mlekiem bezpośrednio przed podaniem."],
    tip: "Przy dietach oznacz osobno mleko bez laktozy i napoje roślinne.",
  },
  {
    name: "Owsianka z owocami", category: "Na słodko", time: "15 min", difficulty: "łatwe",
    ingredients: ["500–600 g płatków owsianych", "1,5–2 l mleka lub wody", "4 banany albo 5 jabłek", "4–5 łyżek miodu lub cukru", "2 łyżeczki cynamonu"],
    steps: ["Zagotuj mleko lub wodę.", "Wsyp płatki i gotuj 5–8 minut, mieszając.", "Dodaj pokrojone owoce.", "Dopraw miodem i cynamonem."],
    tip: "W dużym garnku mieszaj od dna — owsianka łatwo się przypala.",
  },
  {
    name: "Granola z jogurtem i owocami", category: "Ekspresowe", time: "7 min", difficulty: "bardzo łatwe",
    ingredients: ["500–600 g granoli", "1,2–1,5 kg jogurtu naturalnego lub skyru", "4 banany, 5 jabłek lub około 700 g sezonowych owoców", "opcjonalnie: 4 łyżki miodu"],
    steps: ["Rozdziel jogurt do misek.", "Dodaj pokrojone owoce.", "Posyp granolą tuż przed jedzeniem.", "Opcjonalnie polej miodem."],
    tip: "Granolę dodaj na końcu, aby pozostała chrupiąca.",
  },
  {
    name: "Szakszuka", category: "Na ciepło", time: "30 min", difficulty: "średnie",
    ingredients: ["14–16 jajek", "1–1,2 l passaty pomidorowej", "2 cebule", "3 papryki", "3 łyżki oleju", "sól, pieprz i 2 łyżeczki papryki słodkiej", "14–16 kromek pieczywa"],
    steps: ["Podsmaż cebulę i paprykę.", "Dodaj passatę i przyprawy, gotuj około 10 minut.", "Zrób wgłębienia i wbij jajka.", "Przykryj i gotuj do ścięcia białek. Podawaj z pieczywem."],
    tip: "Sos można przygotować wieczorem; rano wystarczy go podgrzać i wbić jajka.",
  },
  {
    name: "Tosty z patelni", category: "Na ciepło", time: "20 min", difficulty: "łatwe",
    ingredients: ["16 kromek chleba tostowego", "8–12 plastrów sera", "8 plastrów szynki lub około 300 g warzyw", "40 g masła"],
    steps: ["Złóż kanapki z serem i dodatkami.", "Posmaruj zewnętrzne strony cienko masłem.", "Smaż na małym ogniu pod przykryciem.", "Obróć i dosmaż do roztopienia sera."],
    tip: "Dociśnij tost łopatką lub drugim, czystym garnkiem.",
  },
  {
    name: "Hot dogi śniadaniowe", category: "Na ciepło", time: "20 min", difficulty: "łatwe",
    ingredients: ["8 bułek do hot dogów", "8 parówek lub parówek wege", "8 plastrów sera", "4 ogórki kiszone", "ketchup i musztarda"],
    steps: ["Podgrzej parówki w wodzie lub na patelni.", "Natnij i ogrzej bułki.", "Włóż parówki oraz dodatki.", "Dodaj sosy bezpośrednio przed podaniem."],
    tip: "Parówki wege podgrzewaj osobno i oznacz, aby nie pomylić paczek.",
  },
  {
    name: "Naleśniki", category: "Na słodko", time: "40 min", difficulty: "średnie",
    ingredients: ["2 szklanki mąki", "2 szklanki mleka", "1 szklanka wody", "4 jajka", "4 łyżki oleju", "1 słoik dżemu lub kremu czekoladowego albo 600 g owoców"],
    steps: ["Wymieszaj mąkę, mleko, wodę i jajka na gładkie ciasto.", "Odstaw na 10 minut, jeśli macie czas.", "Smaż cienkie naleśniki na lekko natłuszczonej patelni.", "Podawaj z wybranymi dodatkami."],
    tip: "Podane proporcje dają około 16–20 naleśników, czyli po 2 sztuki na osobę.",
  },
  {
    name: "Quesadilla z patelni", category: "Na ciepło", time: "18 min", difficulty: "łatwe",
    ingredients: ["8 dużych tortilli", "400–500 g tartego sera", "300 g szynki, 2 puszki kukurydzy lub około 500 g warzyw", "opcjonalnie: 1 słoik salsy"],
    steps: ["Na połowie tortilli rozłóż ser i dodatki.", "Złóż tortillę na pół.", "Smaż bez dużej ilości tłuszczu po 2–3 minuty z każdej strony.", "Pokrój na trójkąty."],
    tip: "Nie wkładaj zbyt wielu mokrych dodatków — tortilla może się rozerwać.",
  },
  {
    name: "Twarożek z rzodkiewką", category: "Bez gotowania", time: "12 min", difficulty: "bardzo łatwe",
    ingredients: ["750–800 g twarogu lub serka kanapkowego", "200 g jogurtu albo śmietany", "2 pęczki rzodkiewek", "1 pęczek szczypiorku", "sól i pieprz", "14–16 kromek pieczywa"],
    steps: ["Rozgnieć twaróg z jogurtem lub śmietaną.", "Pokrój rzodkiewki i szczypiorek.", "Wymieszaj wszystkie składniki.", "Dopraw i podawaj z pieczywem."],
    tip: "W upał przygotuj bezpośrednio przed jedzeniem i nie zostawiaj na słońcu.",
  },
  {
    name: "Serek wiejski z dodatkami", category: "Ekspresowe", time: "7 min", difficulty: "bardzo łatwe",
    ingredients: ["7–8 opakowań serka wiejskiego", "wersja słona: 4 pomidory, 2 ogórki i 1 pęczek szczypiorku", "wersja słodka: 4 banany, 400 g owoców i 4 łyżki miodu", "14–16 kromek pieczywa"],
    steps: ["Rozdziel serek do misek.", "Dodaj wybrane słone lub słodkie dodatki.", "Dopraw wersję słoną pieprzem i solą.", "Podawaj od razu."],
    tip: "Jedna baza pozwala łatwo przygotować równocześnie dwie wersje dla załogi.",
  },
  {
    name: "Guacamole", category: "Bez gotowania", time: "12 min", difficulty: "łatwe",
    ingredients: ["3–4 dojrzałe awokado", "3 pomidory", "1 mała cebula", "sok z 1 cytryny", "sól i pieprz", "14–16 kromek pieczywa lub 8 tortilli"],
    steps: ["Rozgnieć miąższ awokado widelcem.", "Dodaj drobno pokrojony pomidor i cebulę.", "Dopraw sokiem z cytryny, solą i pieprzem.", "Podawaj od razu z pieczywem lub tortillą."],
    tip: "Cytryna poprawia smak i spowalnia ciemnienie awokado.",
  },
];

export const PRODUCTS = [
  ["Chleb pszenny", "Pieczywo", "szt."], ["Chleb razowy", "Pieczywo", "szt."],
  ["Chleb tostowy", "Pieczywo", "opak."], ["Chleb bezglutenowy", "Pieczywo", "szt."],
  ["Bułki kajzerki", "Pieczywo", "szt."], ["Bułki grahamki", "Pieczywo", "szt."],
  ["Bagietki", "Pieczywo", "szt."], ["Tortille", "Pieczywo", "opak."],
  ["Ser gouda w plastrach (lub inny)", "Nabiał i zamienniki", "opak."],
  ["Mozzarella tarta/kulka", "Nabiał i zamienniki", "opak."],
  ["Camembert", "Nabiał i zamienniki", "szt."], ["Ser bez laktozy", "Nabiał i zamienniki", "opak."],
  ["Ser wegański", "Nabiał i zamienniki", "opak."],
  ["Twaróg chudy/tłusty/półtłusty", "Nabiał i zamienniki", "opak."],
  ["Twarożek kanapkowy śmietankowy", "Nabiał i zamienniki", "opak."],
  ["Twarożek Grani", "Nabiał i zamienniki", "opak."],
  ["Hummus", "Nabiał i zamienniki", "opak."], ["Serek wiejski", "Nabiał i zamienniki", "szt."],
  ["Skyr Naturalny", "Nabiał i zamienniki", "szt."], ["Skyr owocowy", "Nabiał i zamienniki", "szt."],
  ["Skyr waniliowy", "Nabiał i zamienniki", "szt."], ["Passata pomidorowa", "Dodatki", "szt."],
  ["Suszone pomidory", "Dodatki", "słoik"], ["Sok do wody", "Dodatki", "butelka"],
  ["Szynka", "Mięso i zamienniki", "opak."], ["Schab w plastrach", "Mięso i zamienniki", "opak."],
  ["Salami", "Mięso i zamienniki", "opak."], ["Kabanosy", "Mięso i zamienniki", "opak."],
  ["Boczek", "Mięso i zamienniki", "opak."], ["Parówki", "Mięso i zamienniki", "paczka 12 szt."],
  ["Pasztet", "Mięso i zamienniki", "opak."],
  ["Wege parówki", "Mięso i zamienniki", "opak."], ["Wege kabanosy", "Mięso i zamienniki", "opak."],
  ["Wege szynka", "Mięso i zamienniki", "opak."], ["Jajka", "Nabiał i zamienniki", "paczka 10 szt."],
  ["Pomidory", "Warzywa", "szt."], ["Ogórki", "Warzywa", "szt."], ["Papryka", "Warzywa", "szt."],
  ["Sałata", "Warzywa", "szt."], ["Rukola", "Warzywa", "opak."], ["Rzodkiewki", "Warzywa", "pęczek"],
  ["Szczypiorek", "Warzywa", "pęczek"], ["Cebula czerwona/żółta", "Warzywa", "szt."],
  ["Awokado", "Warzywa", "szt."], ["Oliwki zielone/czarne", "Warzywa", "słoik"],
  ["Ogórki kiszone", "Warzywa", "słoik"], ["Kukurydza", "Warzywa", "puszka"],
  ["Mleko", "Śniadaniowe", "l"], ["Jogurt naturalny", "Śniadaniowe", "szt."],
  ["Śmietana 18/30", "Śniadaniowe", "szt."], ["Płatki kukurydziane", "Śniadaniowe", "opak."],
  ["Płatki czekoladowe", "Śniadaniowe", "opak."], ["Musli", "Śniadaniowe", "opak."],
  ["Granola", "Śniadaniowe", "opak."], ["Owsianka", "Śniadaniowe", "opak."],
  ["Krem czekoladowy", "Śniadaniowe", "słoik"], ["Dżem", "Śniadaniowe", "słoik"], ["Pasta do smarowania", "Śniadaniowe", "szt."],
  ["Rodzynki", "Śniadaniowe", "opak."], ["Masło", "Śniadaniowe", "szt."],
  ["Wege masło", "Śniadaniowe", "szt."], ["Mąka", "Śniadaniowe", "kg"],
  ["Cukier", "Śniadaniowe", "kg"], ["Cukier wanilinowy", "Śniadaniowe", "opak."],
  ["Banany", "Owoce", "szt."], ["Jabłka", "Owoce", "szt."],
  ["Gruszki", "Owoce", "szt."], ["Winogrona", "Owoce", "opak."],
  ["Borówki", "Owoce", "opak."], ["Maliny", "Owoce", "opak."],
].map(([name, category, unit], index) => ({
  id: `demo-${index + 1}`, name, category, unit, sort_order: index + 1,
}));
