export const CONFIG = {
  SUPABASE_URL: "https://acwzmwvajdavkatohgtr.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjd3ptd3ZhamRhdmthdG9oZ3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxMTE5MTUsImV4cCI6MjA5NzY4NzkxNX0.zJsV29-KH5Uh8OzxGL-9iF59FkJ_sdA_woZJZrKaGn8",
  DEMO_MODE: false,
  TIMEZONE: "Europe/Warsaw",
  ORDER_OPEN_HOUR: 18,
  ORDER_OPEN_MINUTE: 0,
  CUTOFF_HOUR: 9,
  CUTOFF_MINUTE: 30,
  VAPID_PUBLIC_KEY: "BFEFaBJEmpdeVLZ7ueM3DbPYMauYwkziqhVl3ZKFbfBw6PT-cKd-8OHYZc9SFuxLFdPjZIMsgYFcllUKE78dd3w",
};
